version: "3.9"

services:
  api:
    build: .
    container_name: blog_api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16-alpine
    container_name: blog_db
    environment:
      POSTGRES_USER: carana_code
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: blogdb
    ports:
      - "5500:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: