version: "3.9"

services:
  api:
    build: .
    container_name: blog_api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: npm run dev

  db:
    image: postgres:16-alpine
    container_name: blog_db
    environment:
      POSTGRES_USER: carana_code
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: blogdb
    ports:
      - "5500:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carana_code -d blogdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  pgdata: